import {
  Banknote,
  BatteryCharging,
  Baby,
  Bike,
  BusFront,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Cable,
  CakeSlice,
  CarFront,
  ChartNoAxesColumnIncreasing,
  Clapperboard,
  CircleDollarSign,
  Coins,
  Coffee,
  CircuitBoard,
  CookingPot,
  Cpu,
  CreditCard,
  Dumbbell,
  FileText,
  Fuel,
  Gamepad2,
  Gift,
  Globe2,
  GraduationCap,
  Headphones,
  Headset,
  Hammer,
  HandCoins,
  HeartPulse,
  House,
  HousePlug,
  Landmark,
  Laptop,
  Lightbulb,
  MapPin,
  Microwave,
  Monitor,
  Mountain,
  Music2,
  Phone,
  Pill,
  PawPrint,
  Plane,
  PlugZap,
  Receipt,
  School,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sprout,
  Tags,
  TentTree,
  Thermometer,
  Ticket,
  TrainFront,
  Tv,
  Utensils,
  WalletCards,
  Waves,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const categoryIconOptions = [
  { label: "Home", icon: House },
  { label: "Food", icon: Utensils },
  { label: "Shopping", icon: ShoppingBag },
  { label: "Travel", icon: CarFront },
  { label: "Health", icon: HeartPulse },
  { label: "Gifts", icon: Gift },
  { label: "Work", icon: BriefcaseBusiness },
  { label: "Wallet", icon: WalletCards },
  { label: "Plants", icon: Sprout },
  { label: "Online Shopping", icon: ShoppingBag },
  { label: "Shopping Cart", icon: ShoppingCart },
  { label: "Groceries", icon: ShoppingBasket },
  { label: "Coffee", icon: Coffee },
  { label: "Fitness", icon: Dumbbell },
  { label: "Education", icon: GraduationCap },
  { label: "School", icon: School },
  { label: "Degree", icon: GraduationCap },
  { label: "Flights", icon: Plane },
  { label: "Pets", icon: PawPrint },
  { label: "Gaming", icon: Gamepad2 },
  { label: "Music", icon: Music2 },
  { label: "Headphones", icon: Headphones },
  { label: "Headset", icon: Headset },
  { label: "Baby", icon: Baby },
  { label: "Clothing", icon: Shirt },
  { label: "Repairs", icon: Wrench },
  { label: "Internet", icon: Wifi },
  { label: "Cash", icon: Banknote },
  { label: "Books", icon: BookOpen },
  { label: "Phone", icon: Phone },
  { label: "Fuel", icon: Fuel },
  { label: "Bus", icon: BusFront },
  { label: "Movies", icon: Clapperboard },
  { label: "Electronics", icon: CircuitBoard },
  { label: "Gadgets", icon: Cpu },
  { label: "Laptop", icon: Laptop },
  { label: "Monitor", icon: Monitor },
  { label: "Television", icon: Tv },
  { label: "Maintenance", icon: Hammer },
  { label: "Building", icon: Building },
  { label: "Office", icon: Building2 },
  { label: "Temperature", icon: Thermometer },
  { label: "Electricity", icon: HousePlug },
  { label: "Battery", icon: BatteryCharging },
  { label: "Kitchen", icon: CookingPot },
  { label: "Cutlery", icon: Utensils },
  { label: "Microwave", icon: Microwave },
  { label: "Camping", icon: TentTree },
  { label: "Hiking", icon: Mountain },
  { label: "Trekking", icon: Mountain },
  { label: "Cable", icon: Cable },
  { label: "Power", icon: PlugZap },
  { label: "Lighting", icon: Lightbulb },
];

const categoryIconMap: Record<string, LucideIcon> = {
  ...Object.fromEntries(categoryIconOptions.map(({ label, icon }) => [label, icon])),
  Plants: Sprout, Home: House, Housing: House, Food: Utensils, "Food & Drinks": Utensils,
  "Online Shopping": ShoppingBag, OnlineShopping: ShoppingBag, ShoppingBag,
  Shopping: ShoppingCart, "Shopping Cart": ShoppingCart, ShoppingCart,
  Groceries: ShoppingBasket, Travel: CarFront, Flights: Plane, Health: HeartPulse,
  Fitness: Dumbbell, "Fitness & Sports": Dumbbell, Gifts: Gift, Work: BriefcaseBusiness,
  Wallet: WalletCards, Cash: Banknote, Education: GraduationCap, Pets: PawPrint, Pet: PawPrint,
  Movies: Clapperboard, "Movies & Entertainment": Clapperboard, "Entertainment & Movies": Clapperboard,
  Insurance: ShieldCheck, Car: CarFront, Transport: TrainFront, Vehicles: Bike,
  Salary: CircleDollarSign, Freelancing: Laptop, Investments: ChartNoAxesColumnIncreasing,
  FD: Coins, Loans: HandCoins, Family: Baby, Entertainment: Gamepad2, Music: Music2,
  Restaurants: Utensils, Coffee, Clothing: Shirt, Bills: FileText, Utilities: Zap,
  Rent: Building2, Phone, Internet: Wifi, Subscriptions: Ticket, Fuel, Medicine: Pill,
  Bank: Landmark, Savings: WalletCards, CreditCard, TravelMap: MapPin, Vacation: Globe2,
  Repairs: Wrench, Events: CakeSlice, Charity: HandCoins, Hobbies: Waves, Receipts: Receipt,
  Books: BookOpen,
};

const categoryForegroundMap: Record<string, string> = {
  "#e3eee9": "#356b68", "#f8e9e6": "#9e514b", "#f3e8d4": "#95631e",
  "#e3eff6": "#436f9a", "#e5f3eb": "#2f7d5a", "#ece6f3": "#735b8f", "#fbe8dc": "#a9512e",
};

export function getCategoryIcon(icon: string | null | undefined, name?: string) {
  return (icon && categoryIconMap[icon]) || (name && categoryIconMap[name]) || Tags;
}

export function getCategoryForeground(color: string | null | undefined) {
  return categoryForegroundMap[color?.toLowerCase() ?? ""] ?? "#356b68";
}
