import { and, eq, isNull, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { errorResponse, requireAccessToken } from "@/backend/auth/http";
import { db } from "@/backend/db/client";
import { savingsInstrumentTypes, savingsInstruments } from "@/backend/db/schema";
import { savingsInstrumentInput } from "@/backend/domain/validation";
import { deleteUploadIfUnreferenced, prepareStoredObjectAttachment, prepareStoredObjectDetachment, type UploadBatchStatement } from "@/backend/storage/upload-lifecycle";
import { normalizeMoney } from "@/lib/money";

type Context = { params: Promise<{ id: string }> };
export async function GET(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const [instrument] = await db.select().from(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).limit(1); if (!instrument) return errorResponse("Savings instrument not found", 404); const [type] = await db.select().from(savingsInstrumentTypes).where(eq(savingsInstrumentTypes.id, instrument.typeId)).limit(1); return NextResponse.json({ instrument: { ...instrument, currentBalance: normalizeMoney(instrument.currentBalance), typeName: type?.name ?? "Other" } }); }
export async function PATCH(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const [current] = await db.select({ icon: savingsInstruments.icon }).from(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).limit(1); if (!current) return errorResponse("Savings instrument not found", 404); const parsed = savingsInstrumentInput.partial().safeParse(await request.json().catch(() => null)); if (!parsed.success || Object.keys(parsed.data).length === 0) return errorResponse("Invalid savings instrument update", 400); if (parsed.data.typeId) { const [type] = await db.select().from(savingsInstrumentTypes).where(and(eq(savingsInstrumentTypes.id, parsed.data.typeId), or(eq(savingsInstrumentTypes.userId, userId), isNull(savingsInstrumentTypes.userId)))).limit(1); if (!type) return errorResponse("Savings instrument type not found", 400); } let attachmentStatement; try { attachmentStatement = await prepareStoredObjectAttachment(userId, "savings-images", parsed.data.icon, "savings_instrument", id); } catch (error) { return errorResponse(error instanceof Error ? error.message : "Invalid savings image", 400); } const detachmentStatement = Object.prototype.hasOwnProperty.call(parsed.data, "icon") && current.icon !== parsed.data.icon ? await prepareStoredObjectDetachment(userId, "savings-images", current.icon, "savings_instrument", id) : null; const updateInstrument = db.update(savingsInstruments).set(parsed.data).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).returning({ id: savingsInstruments.id }); const statements: UploadBatchStatement[] = []; if (attachmentStatement) statements.push(attachmentStatement); statements.push(updateInstrument as unknown as UploadBatchStatement); if (detachmentStatement) statements.push(detachmentStatement); await db.batch(statements as [UploadBatchStatement, ...UploadBatchStatement[]]); const [updated] = await db.select().from(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).limit(1); if (!updated) return errorResponse("Savings instrument not found", 404); if (current.icon !== updated.icon) await deleteUploadIfUnreferenced(userId, "savings-images", current.icon).catch((error) => console.error("Savings image cleanup failed", { userId, id, error })); return NextResponse.json({ instrument: { ...updated, currentBalance: normalizeMoney(updated.currentBalance) } }); }
export async function DELETE(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const [current] = await db.select({ icon: savingsInstruments.icon }).from(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).limit(1); if (!current) return errorResponse("Savings instrument not found", 404); const detachmentStatement = await prepareStoredObjectDetachment(userId, "savings-images", current.icon, "savings_instrument", id); const deleteInstrument = db.delete(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).returning({ id: savingsInstruments.id }); await db.batch(detachmentStatement ? [deleteInstrument, detachmentStatement] : [deleteInstrument]); await deleteUploadIfUnreferenced(userId, "savings-images", current.icon).catch((error) => console.error("Savings image cleanup failed", { userId, id, error })); return NextResponse.json({ success: true }); }
