import { and, eq, isNull, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { errorResponse, requireAccessToken } from "@/backend/auth/http";
import { db } from "@/backend/db/client";
import { savingsInstrumentTypes, savingsInstruments } from "@/backend/db/schema";
import { savingsInstrumentInput } from "@/backend/domain/validation";
import { normalizeMoney } from "@/lib/money";

export const runtime = "nodejs"; type Context = { params: Promise<{ id: string }> };
export async function GET(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const [instrument] = await db.select().from(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).limit(1); if (!instrument) return errorResponse("Savings instrument not found", 404); const [type] = await db.select().from(savingsInstrumentTypes).where(eq(savingsInstrumentTypes.id, instrument.typeId)).limit(1); return NextResponse.json({ instrument: { ...instrument, currentBalance: normalizeMoney(instrument.currentBalance), typeName: type?.name ?? "Other" } }); }
export async function PATCH(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const parsed = savingsInstrumentInput.partial().safeParse(await request.json().catch(() => null)); if (!parsed.success || Object.keys(parsed.data).length === 0) return errorResponse("Invalid savings instrument update", 400); if (parsed.data.typeId) { const [type] = await db.select().from(savingsInstrumentTypes).where(and(eq(savingsInstrumentTypes.id, parsed.data.typeId), or(eq(savingsInstrumentTypes.userId, userId), isNull(savingsInstrumentTypes.userId)))).limit(1); if (!type) return errorResponse("Savings instrument type not found", 400); } const updated = await db.update(savingsInstruments).set(parsed.data).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).returning(); if (!updated.length) return errorResponse("Savings instrument not found", 404); return NextResponse.json({ instrument: { ...updated[0], currentBalance: normalizeMoney(updated[0].currentBalance) } }); }
export async function DELETE(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const deleted = await db.delete(savingsInstruments).where(and(eq(savingsInstruments.id, id), eq(savingsInstruments.userId, userId))).returning({ id: savingsInstruments.id }); return deleted.length ? NextResponse.json({ success: true }) : errorResponse("Savings instrument not found", 404); }
