import { and, eq, isNull, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { errorResponse, requireAccessToken } from "@/backend/auth/http";
import { db } from "@/backend/db/client";
import { accounts, categories, recurringTemplates } from "@/backend/db/schema";
import { recurringTemplateInput } from "@/backend/domain/validation";

export const runtime = "nodejs"; type Context = { params: Promise<{ id: string }> };
export async function PATCH(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const parsed = recurringTemplateInput.partial().safeParse(await request.json().catch(() => null)); if (!parsed.success || Object.keys(parsed.data).length === 0) return errorResponse("Invalid recurring template update", 400); if (parsed.data.accountId) { const [account] = await db.select().from(accounts).where(and(eq(accounts.id, parsed.data.accountId), eq(accounts.userId, userId))).limit(1); if (!account) return errorResponse("Account not found", 400); } if (parsed.data.categoryId) { const [category] = await db.select().from(categories).where(and(eq(categories.id, parsed.data.categoryId), or(eq(categories.userId, userId), isNull(categories.userId)))).limit(1); if (!category) return errorResponse("Category not found", 400); } const updated = await db.update(recurringTemplates).set(parsed.data).where(and(eq(recurringTemplates.id, id), eq(recurringTemplates.userId, userId))).returning(); if (!updated.length) return errorResponse("Recurring template not found", 404); return NextResponse.json({ recurringTemplate: updated[0] }); }
export async function DELETE(request: Request, { params }: Context) { const userId = await requireAccessToken(request); const { id } = await params; if (!userId) return errorResponse("Authentication required", 401); const deleted = await db.delete(recurringTemplates).where(and(eq(recurringTemplates.id, id), eq(recurringTemplates.userId, userId))).returning({ id: recurringTemplates.id }); return deleted.length ? NextResponse.json({ success: true }) : errorResponse("Recurring template not found", 404); }
