import { BarChart3, HandCoins, Landmark, LineChart, Repeat2, Tags, Target, WalletCards } from "lucide-react";
import type { FeatureGuideConfig } from "./feature-guide";

export const featureGuides = {
  categories: {
    path: "/categories",
    label: "Categories",
    title: "Category guide",
    eyebrow: "Organize activity",
    icon: Tags,
    summary: "Give every transaction a clear place.",
    why: "Categories group income and expenses so you can understand your spending, compare periods, and find transactions quickly.",
    steps: [
      { title: "Create a category", description: "Add a name, choose income or expense, and pick an icon and color." },
      { title: "Use it when recording", description: "Select the category while adding a transaction so the activity is grouped correctly." },
      { title: "Review the pattern", description: "Open Analytics to see which categories take the largest share of your spending." },
    ],
    example: { title: "A food budget", subtitle: "Food & Drinks", amount: "NPR 1,200", rows: [{ label: "Lunch", value: "−NPR 800", tone: "expense" }, { label: "Coffee", value: "−NPR 400", tone: "expense" }] },
  },
  loans: {
    path: "/loans",
    label: "Loans",
    title: "Loan guide",
    eyebrow: "Track repayment",
    icon: HandCoins,
    summary: "Keep borrowed and lent money separate.",
    why: "Loans track who owes whom, the remaining principal, repayment dates, interest terms, and the payments that reduce the balance.",
    steps: [
      { title: "Choose the direction", description: "Select I owe when you borrowed money, or Owed to me when someone borrowed from you." },
      { title: "Add the principal", description: "Enter the original amount, account, currency, and any repayment plan details." },
      { title: "Record each payment", description: "Add repayments as they happen. Luna updates the outstanding balance and marks paid-off loans separately." },
    ],
    example: { title: "A laptop loan", subtitle: "Laptop loan · I owe", amount: "NPR 25,000", rows: [{ label: "Original principal", value: "NPR 30,000" }, { label: "Payment recorded", value: "−NPR 5,000", tone: "expense" }, { label: "Remaining", value: "NPR 25,000", tone: "primary" }] },
  },
  savings: {
    path: "/savings-instruments",
    label: "Saving Instruments",
    title: "Savings guide",
    eyebrow: "Track money set aside",
    icon: Landmark,
    summary: "Give savings a place and a purpose.",
    why: "Saving instruments track money held for a longer-term purpose, such as an emergency fund, fixed deposit, or planned purchase.",
    steps: [
      { title: "Add an instrument", description: "Name the place or purpose, choose its type, currency, and starting balance." },
      { title: "Keep its balance current", description: "Record additions, withdrawals, and adjustments so the displayed balance stays useful." },
      { title: "Watch important dates", description: "Add a maturity date when one exists so it is easy to see what needs attention next." },
    ],
    example: { title: "An emergency fund", subtitle: "Emergency fund · Savings", amount: "NPR 20,000", rows: [{ label: "Starting balance", value: "NPR 15,000" }, { label: "Added this month", value: "+NPR 5,000", tone: "income" }, { label: "Maturity date", value: "Not set" }] },
  },
  goals: {
    path: "/goals",
    label: "Goals",
    title: "Goal guide",
    eyebrow: "Plan a future purchase",
    icon: Target,
    summary: "Turn a target into small, trackable moves.",
    why: "Goals show how much has been allocated, what remains, and which account holds the money. Contributions and withdrawals stay traceable.",
    steps: [
      { title: "Set a target", description: "Name the goal, enter the target amount, and choose the goal account that will hold it." },
      { title: "Add or withdraw funds", description: "Move money between a spendable account and the goal account as your plan changes." },
      { title: "Mark the purchase", description: "When a completed goal is spent, record it without charging the source account a second time." },
    ],
    example: { title: "A new laptop", subtitle: "Laptop fund · Active", amount: "NPR 50,000", rows: [{ label: "Target", value: "NPR 80,000" }, { label: "Allocated", value: "NPR 50,000", tone: "primary" }, { label: "Still needed", value: "NPR 30,000" }] },
  },
  recurring: {
    path: "/recurring",
    label: "Recurring",
    title: "Recurring guide",
    eyebrow: "Schedule repeat activity",
    icon: Repeat2,
    summary: "Set up transactions that happen on a schedule.",
    why: "Recurring templates prepare regular income, expenses, savings, and transfers so you do not have to rebuild the same transaction each time.",
    steps: [
      { title: "Create the template", description: "Choose the type, amount, account, category, frequency, and next date." },
      { title: "Choose a review mode", description: "Keep Ask before posting on for approval, or turn it off when automatic posting is appropriate." },
      { title: "Handle each occurrence", description: "Review, post, skip, pause, or resume items from Upcoming and Needs your attention." },
    ],
    example: { title: "A monthly expense", subtitle: "Monthly rent · Every month", amount: "−NPR 25,000", rows: [{ label: "Next date", value: "Aug 15, 2026" }, { label: "Category", value: "Housing" }, { label: "Posting", value: "Review before posting" }] },
  },
  reports: {
    path: "/reports",
    label: "Reports",
    title: "Report guide",
    eyebrow: "Review your money",
    icon: BarChart3,
    summary: "Use a saved summary to make better decisions.",
    why: "Reports combine spending, earning, savings, major expenses, forecasts, and practical suggestions for a selected period.",
    steps: [
      { title: "Choose a period", description: "Switch between weekly, monthly, and yearly views to change the time window." },
      { title: "Read the details", description: "Check totals, category breakdowns, largest expenses, forecast, and insights together." },
      { title: "Refresh when needed", description: "Reports load the saved result. Use Refresh after new activity to calculate and store an updated result." },
    ],
    example: { title: "A monthly check-in", subtitle: "August report", amount: "NPR 42,500 saved", rows: [{ label: "Spending", value: "NPR 28,000", tone: "expense" }, { label: "Earning", value: "NPR 70,500", tone: "income" }, { label: "Savings", value: "NPR 42,500", tone: "primary" }] },
  },
  transactions: {
    path: "/transactions",
    label: "Transactions",
    title: "Transaction guide",
    eyebrow: "Keep activity accurate",
    icon: WalletCards,
    summary: "Record what happened and where the money moved.",
    why: "Transactions are the source for account balances, analytics, goals, reports, and recurring activity. Accurate entries keep every view aligned.",
    steps: [
      { title: "Choose the type", description: "Start with expense, income, savings, or transfer so Luna applies the right balance rules." },
      { title: "Enter the details", description: "Add the amount, account, category, date, and a useful title or note." },
      { title: "Review the activity", description: "Use filters and search to find entries, then open one to edit or inspect its history." },
    ],
    example: { title: "A recorded expense", subtitle: "Groceries", amount: "−NPR 2,000", rows: [{ label: "Account", value: "Everyday account" }, { label: "Category", value: "Food & Drinks" }, { label: "Date", value: "Aug 8, 2026" }] },
  },
  analytics: {
    path: "/analytics/income",
    label: "Analytics",
    title: "Analytics guide",
    eyebrow: "Understand the pattern",
    icon: LineChart,
    summary: "See where money came from and where it went.",
    why: "Analytics turns transactions into period-based views for income, expenses, savings, categories, and the activity behind each number.",
    steps: [
      { title: "Choose a view", description: "Switch between income, expenses, and savings to focus on one part of your cash flow." },
      { title: "Set the period", description: "Use the filter to compare a month, a custom range, or all available activity." },
      { title: "Open the details", description: "Review the chart and related transactions together to understand the result." },
    ],
    example: { title: "A monthly overview", subtitle: "August cash flow", amount: "+NPR 12,500", rows: [{ label: "Income", value: "NPR 70,500", tone: "income" }, { label: "Expenses", value: "NPR 58,000", tone: "expense" }, { label: "Cash flow", value: "+NPR 12,500", tone: "primary" }] },
  },
} satisfies Record<string, FeatureGuideConfig>;
